import type { NextPage, GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { useRouter } from 'next/router'
import AppCardGroup from '../../components/AppCardGroup';
import { apiClient } from '@/lib/api';

function Device(props:devicePropsType) {

  const router = useRouter()
  const { deviceToken } = router.query

  return (
    <div className={styles.container}>
      <Head>
        <title>Search results for {deviceToken} - iconpusher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppCardGroup
        appCards={props.results.apps}
        // moreLink={moreLink}
        onAdd={props.onAdd}
        onRemove={props.onRemove}
        onCheckSelected={props.onCheckSelected}
        setSearchKeyword={props.setSearchKeyword}
        useMax={false}
      />
    </div>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  if (context.params != undefined && context.params.deviceToken != undefined) {
    // Fetch data from external API
    const results = await apiClient.get(`/device/${context.params.deviceToken}`)

    // Pass data to the page via props
    return { props: { results } }
  }
    return {props:{}}
  }


export default Device
// SearchResult.Layout = MyLayout;